config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  root 'home#index'

  get 'player/:id' => 'home#show_player', as: :show_player
  get 'admin' => 'admin#rank', as: :rank

  resources :players do
      collection do
        get 'stats/:id' => 'players#stats', as: :player_stats
      end
    end
  resources :matches do
    collection do
      get '/search' => "matches#search", as: :search_matches
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'

	def index
	  @matches = Match.first(8)
      @players = Player.list
      @chart = Chart.first[:chart]
	end

	def show_player
		logger.info id = params[:id]
		@player = Player.find_by(:id =>id)

		if @player.points.exists?
			chart = Chart.first[:chart]
			@pos = chart[id.to_i][:curr_position]
			@pts = chart[id.to_i][:sum]

			m_wins = @player.loss_win('w')
			@mw_tab = Hash.new
			# opponent points
			m_wins.each_with_index do |mw,i|
				logger.info "================"
				logger.info mw
				match = Match.find_by(:id => mw)
				if match.player1_id == @player.id
					p = Player.find_by(:id => match.player2_id)
					@mw_tab[i] = [p.name_with_initial, match.player2_res]
				else
					p = Player.find_by(:id => match.player1_id)
					@mw_tab[i] = [p.name_with_initial, match.player1_res]
				end
			end

			m_losses = @player.loss_win('l')
			@ml_tab = Hash.new
			# opponent points
			m_losses.each_with_index do |mw,i|
				logger.info "================"
				logger.info mw
				match = Match.find_by(:id => mw)
				if match.player1_id == @player.id
					p = Player.find_by(:id => match.player2_id)
					@ml_tab[i] = [p.name_with_initial, match.player2_res]
				else
					p = Player.find_by(:id => match.player1_id)
					@ml_tab[i] = [p.name_with_initial, match.player1_res]
				end
			end
		end
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_last_matches.erb
        <% @matches.each do |match| %>
            <tr>
                <td class="t-center" id="player_date" colspan="5"><%= match.day %></td>
            </tr>
            <tr>                
                <td class="t-right" id="player">
                    <div><%= Player.find(match.player1_id).f_name %> </div><div><%= Player.find(match.player1_id).l_name %></div>
                    <div><%= match.player1_res %></div>
                </td>
                <td class="t-center star"><%= match.winner_id == match.player1_id ? " ★ " : ""%></td>
                <td class="t-center" id="player_vs"> VS </td>
                <td class="t-center star"><%= match.winner_id == match.player2_id ? " ★ " : ""%></td>
                <td class="t-left" id="player">
                    <div><%= Player.find(match.player2_id).f_name %> </div><div><%= Player.find(match.player2_id).l_name %></div>
                    <div><%= match.player2_res %></div>
                </td>
                </tr>
        <% end %>

app/views/home/_player_owl.html.erb
<div id="owl-custom">
	<% @players.each do |p| %>       
  		<div class="item">
  		<%= link_to show_player_path(p) do %>
  			<%= p.avatar.present? ? image_tag(p.avatar.thumb) : image_tag("def.jpeg", class: "owl_img")%>
  			<div class="t-center"><%= p.f_name%> <%=p.l_name%></div>
  			<%end%>
  		</div> 
  		<% end %>
</div>

app/views/home/_rank_table.html.erb
    <table class="rank_tab" cellspacing="0" cellpadding="0" width="100%">
      <thead>
        <tr>
          <th class="t-center player"> # </th>
          <th>PLAYER</th>
          <th></th>
          <th>POINTS</th>
        </tr>
      </thead>

      <tbody>
        <% @chart.each do |k,v| %>
          <tr>
          <td class="t-center rank_tab2"><%= v[:curr_position]  %>
            <td class="t-center player rank_tab3"><%= v[:f_name] %> <%= v[:l_name] %> </td>
            <td class=" rank_tab4">
              <%  if v[:curr_position] < v[:prev_position] %>
                <div class="arrow_position up"><%=  "▲" %> </div>
              <% elsif v[:curr_position] > v[:prev_position] && v[:prev_position] != -1 %>
                <div class="arrow_position down"><%= "▼" %></div>
              <% else%>
                <div><%= "■" %></div>
              <% end %>
            </td>
            <td class="t-center rank_tab2"><%= v[:sum] %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

app/views/home/index.html.erb
<div class="main-panel"><%= render "shared/home" %></div>

app/views/home/show_player.html.erb
<div class="main-panel add_margin">
	<div class="content_player add_padd">
		<div class="row">
			<div class="col-xs-6 col-md-4 col-lg-3 round_av "><%=  @player.avatar.present? ? image_tag( @player.avatar.thumb) : image_tag("def.jpeg", class: "owl_img")%></div>
		  <% if  @player.points.exists? %>
		  	<div class="col-xs-12 col-sm-6 col-md-8 col-lg-9">
		  		<div class="page-header add_margin with_star">
  					<h1><%= @player.f_name.upcase %> <%= @player.l_name.upcase %> <small>PLAYER FROM <%= @player.created_at.strftime("%B %d, %Y") %></small></h1>
  					<div class="leader"><%= @pos == 1 ? "♛" : "" %></div>
				</div>
		  	</div>
		</div>
		<div class="row add_margin add_margin_lr">
  			<div class="col-xs-6 pos_rank" style="font-size: 90px">#<%= @pos %></div>
  			<div class="col-xs-6 ">
  				<div class="panel panel-default">
				  <div class="panel-heading">LAST MATCH : 
				  <%= @player.last_match.winner_id == @player.id ? "WIN" : "LOSS" %>
				  </div>
				  <div class="panel-body table-responsive">
				    <table class="table">
			  			<tr>
	        				<td class="t-center" id="" colspan="3"><%= @player.last_match.day %></td>
	    				</tr>
	            		<tr>                
	                		<td class="t-center" id="player">
	                    		<div><%= Player.find(@player.last_match.player1_id).f_name %> <%= Player.find(@player.last_match.player1_id).l_name %></div>
	                   			<div><%= @player.last_match.player1_res %></div>
	                		</td>
	                		<td class="t-center" id=""> VS </td>
	                		<td class="t-center" id="player">
	                    		<div><%= Player.find(@player.last_match.player2_id).f_name %> <%= Player.find(@player.last_match.player2_id).l_name %></div>
	                    		<div><%= @player.last_match.player2_res %></div>
	                		</td>
						</tr>
					</table>
				  </div>
				</div>
  			</div>
		</div>
		<div class="row add_margin add_margin_lr">
			<div class="col-xs-3 ">
  				<div class="panel panel-default">
				  <div class="panel-body">
				    <%= @pts%>
				  </div>
				  <div class="panel-footer">POINTS</div>
				</div>
  			</div>
  			<div class="col-xs-3 ">
  				<div class="panel panel-default">
				  <div class="panel-body">
				    <%= @player.wins %>
				  </div>
				  <div class="panel-footer">WINS</div>
				</div>
  			</div>
  			<div class="col-xs-3">
  				<div class="panel panel-default">
				  <div class="panel-body">
				    <%= @player.losses %>
				  </div>
				  <div class="panel-footer">LOSSES </div>
				</div>
  			</div>
  			<div class="col-xs-3 ">
  				<div class="panel panel-default">
				  <div class="panel-body">
				    <%= @player.all_matches.count %>
				  </div>
				  <div class="panel-footer">ALL MATCHES</div>
  				</div>
			</div>
		</div>
		<div class="row add_margin add_margin_lr">
  			<div class="col-xs-3 "></div>
  			<div class="col-xs-6 add_margin_lr"></div>
  			<div class="col-xs-3 "></div>
		</div>
		<% else %>
		<div class="row add_margin_lr">
	  		<div class="col-xs-12 t-center"> 
	  		BRAK DANYCH
	  		</div>
		</div>
		<%end%>
		<div class="col-xs-12 t-center">
  				<%= link_to "BACK", root_url%>
  			</div>
	</div>
</div>