config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  root 'home#index'

  get 'player/:id' => 'home#show_player', as: :show_player
  get 'admin' => 'admin#rank', as: :rank

  resources :players do
      collection do
        get 'stats/:id' => 'players#stats', as: :player_stats
      end
    end
  resources :matches do
    collection do
      get '/search' => "matches#search", as: :search_matches
    end
  end

end

app/models/player.rb
class Player < ActiveRecord::Base

  mount_uploader :avatar, AvatarUploader
	has_many :player1_matches, class_name: "Match", foreign_key: "player1_id", dependent: :destroy
	has_many :player2_matches, class_name: "Match", foreign_key: "player2_id", dependent: :destroy
	has_many :points, dependent: :destroy	
  validates_presence_of :f_name, :l_name
  scope :list, -> {order("l_name ASC")}

  # returns first letter from first name and full last name
  def name_with_initial
    "#{f_name.first}. #{l_name}"
  end

  # returns the number of matches
  def all_matches
    player1_matches + player2_matches
  end

  # returns players points
  def sum_value
    sum = 0
    points.each do |v|
      sum += v.value
    end
    sum
  end

  # returns the last players match
  def last_match
    all_matches.last
  end

  # returns the number of wins
  def wins
    counter = 0
    all_matches.each do |m|
      if m.winner_id == id
        counter += 1
      end
    end
    counter
  end

  # returns the number of losses
  def losses
    counter = 0
    all_matches.each do |m|
      if m.loser_id == id
        counter += 1
      end
    end
    counter
  end

  # returns table which contains ids of win matches or lost matches, 
  # depends on passed params, w for wins, l for losses
  def loss_win(res)
    tab = []
    all_matches.each do |m|

      if res == 'w'
        if m.winner_id == id
          tab << m.id
        end
      end

      if res == 'l'
        if m.loser_id == id
          tab << m.id
        end
      end

    end
    tab
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  layout 'user'
  before_action :authenticate_user!
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.paginate(:page => params[:page], :per_page => 5)
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to players_url, notice: 'Player was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to players_url, notice: 'Player was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def stats
    @player = Player.find_by(:id => params[:id])
    @matches = @player.all_matches
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:f_name, :l_name, :avatar, :points)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'First name' %><br>
    <%= f.text_field :f_name %>
  </div>
  <div class="field">
    <%= f.label 'Last name' %><br>
    <%= f.text_field :l_name %>
  </div>

  <% if @player.avatar.present?%>
      <%= image_tag @player.avatar.thumb %>
    <%end%>
  <div class="field">
    <%= f.label 'Photo' %><br>
    <%= f.file_field :avatar %>
  </div>
    <div class="actions">
    <% if action_name == 'edit' || request.method == "POST"%>
      <%= f.submit 'UPDATE', :class => 'btn btn-success' %>
    <% elsif action_name == 'new'%>
      <%= f.submit 'ADD', :class => 'btn btn-success' %>
    <% end %>
    <%= link_to 'CALNCEL', players_path, :class => "btn btn-warning" %>
  </div>
<% end %>

app/views/players/edit.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Editing Player</h3>
  </div>
   <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">PLAYERS
  </div>
  <div class="panel-body">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Avatar</th>
          <th>First name</th>
          <th>Last name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @players.each do |player| %>
          <tr>
            <td><%= player.avatar.present? ? image_tag(player.avatar.thumb) : image_tag("def.jpeg", class: "list_img")%></td>
            <td><%= player.f_name %></td>
            <td><%= player.l_name %></td>
            <td><%= link_to 'Statistics', player_stats_players_path(player) %></td>
            <td><%= link_to 'Edit', edit_player_path(player) %></td>
            <td><%= link_to 'Delete', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  </div>
</div>
      <div><%= will_paginate @players %></div><br>
<%= link_to 'Add new player', new_player_path, :class => "btn btn-info" %>

app/views/players/new.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">New Player</h3>
  </div>
   <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/players/stats.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-default">
  <div class="panel-heading">Stats for player: <%= @player.name_with_initial %>
  </div>
  <div class="panel-body">
    <table class="table">
      <thead>
        <tr>
          <th>Points</th>
          <th>All Matches</th>
          <th>Victory</th>
          <th>Defeat</th>
        </tr>
      </thead>

      <tbody>
          <tr>
            <td><%= @player.sum_value %></td>
            <td><%= @player.all_matches.count %></td>
            <td><%= @player.wins %></td>
            <td><%= @player.losses %></td>
          </tr>
      </tbody>
    </table>
    <h5> MATCHES </h5>
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Player 1</th>
          <th></th>
          <th>  </th>
          <th></th>
          <th>Player 2</th>
          <th> VICTORY or DEFEAT </th>
        </tr>
      </thead>

      <tbody>
        <% @matches.each do |match| %>
        <tr>
            <td><%= match.day %></td>
            <td><%= Player.find(match.player1_id).name_with_initial %></td>
            <td><%= match.player1_res %></td>
            <td> : </td>
            <td><%= match.player2_res %></td>
            <td><%= Player.find(match.player2_id).name_with_initial %></td>
            <td> <%= match.winner_id == @player.id ? "VICTORY" : "DEFEAT" %>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>