config/routes.rb
Rails.application.routes.draw do

  
  devise_for :users
  root 'home#index'

  get 'player/:id' => 'home#show_player', as: :show_player
  get 'admin' => 'admin#rank', as: :rank

  resources :players do
      collection do
        get 'stats/:id' => 'players#stats', as: :player_stats
      end
    end
  resources :matches do
    collection do
      get '/search' => "matches#search", as: :search_matches
    end
  end

end

app/models/match.rb
class Match < ActiveRecord::Base

	belongs_to :player1, class_name: "Player", foreign_key: "player1_id"
	belongs_to :player2, class_name: "Player", foreign_key: "player2_id"
	has_many :points, dependent: :destroy
	validates_presence_of :player1_id, :player2_id, :date, :player1_res, :player2_res
	validates :player1_res, :player2_res, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 10 }
	validate :the_point, :the_player
	default_scope { order('date DESC') }

	# returns the day of the match
	def day
		date.strftime("%d.%m.%y")
	end

	# returns the match winner id 
	def winner_id
		player1_res > player2_res ? player1_id : player2_id
	end

	# returns the match losser id
	def loser_id
		player1_res < player2_res ? player1_id : player2_id
	end

	# generates Points for match Players
	def generate_points
	  Point.new(:match_id => id, :player_id => player1_id, :value => (10 - player2_res)).save!
      Point.new(:match_id => id, :player_id => player2_id, :value => (10 - player1_res)).save!
	end

	# update points after update the match
	def update_value
	  points[0].update(:player_id => player1_id, :value => (10 - player2_res))
	  points[1].update(:player_id => player2_id, :value => (10 - player1_res))
	end

	# returns matches for selected players in dropdown select
	def self.search(p1,p2)
	  if Match.count != 0
		  if p1.empty? && p2.empty?
		  	all
		  elsif p1.present? && p2.empty?
		  	where(:player1_id => p1)
		  elsif p1.empty? && p2.present?
		  	where(:player2_id => p2)
		  else
		   	where("player1_id LIKE ? AND player2_id LIKE ?", p1, p2)
		  end
	  end
	end

	# validation for results
	def the_point
		if player1_res < 10 && player2_res < 10
			self.errors.add(:player1_res," - one of the results must be 10!")
			self.errors.add(:player2_res," - one of the results must be 10!")
		end
		if player1_res == 10 && player2_res == 10
			self.errors.add(:player1_res, " - just one of the results must be 10!")
			self.errors.add(:player2_res, " - just one of the results must be 10!")
		end
	end

	# validation for player_id
	def the_player
		if player1_id == player2_id
			self.errors.add(:player1_id," - please, change Players")
			self.errors.add(:player2_id, " - please, change Players")
		end
	end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  layout 'user'
  before_action :authenticate_user!
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.paginate(:page => params[:page], :per_page => 10)
    @players = Player.all
  end

  # GET /matches/new
  def new
    @match = Match.new
    @players_list = Player.all
  end

  # GET /matches/1/edit
  def edit
    @players_list = Player.all
  end

  # POST /matches
  # POST /matches.json
  def create
    @players_list = Player.all
    @match = Match.new(match_params)

    respond_to do |format|
        if @match.save
          @match.generate_points  
          prev_chart = Chart.first[:chart]    
          Chart.first.update(:chart => Point.get_rank(prev_chart))  
          format.html { redirect_to matches_url, notice: 'Match was successfully created.' }
        else
          format.html { render :new }
          format.json { render json: @match.errors, status: :unprocessable_entity }
        end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    @players_list = Player.all
    respond_to do |format|
      if @match.update(match_params) &&  @match.update_value
        prev_chart = Chart.first[:chart]    
        Chart.first.update(:chart => Point.get_rank(prev_chart)) 
        format.html { redirect_to matches_url, notice: 'Match was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @matches = Match.search(params[:player1_id],params[:player2_id])
      respond_to do |format|
        format.js
      end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:date, :player1_id, :player2_id, :player1_res, :player2_res)
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_form.html.erb
<%= form_for(@match) do |f| %>

  <% if @match.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
      <% @match.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field date">
    <label>Data</label>
    <%= f.datetime_select :date %>
  </div>

  <div class="create-match">
    <div class="hosts"> 
      <div class="field team">
        <label>Player_1</label>
        <%= f.collection_select(:player1_id, @players_list, :id, :name_with_initial) %>
      </div>

      <div class="field result">
        <label>Points</label>
        <%= f.text_field :player1_res, :placeholder => "-" %>
      </div>
    </div>

    <div class="versus">vs</div>

    <div class="guests">        
      <div class="field team">
        <label>Player_2</label>
        <%= f.collection_select(:player2_id, @players_list, :id, :name_with_initial) %>
      </div>
      <div class="field result">
        <label>Points</label>
        <%= f.text_field :player2_res, :placeholder => "-" %>
      </div>
    </div>
  </div>

  <div class="actions">
    <% if action_name == 'edit' || request.method == "POST"%>
      <%= f.submit 'UPDATE', :class => 'btn btn-success' %>
    <% elsif action_name == 'new'%>
      <%= f.submit 'ADD', :class => 'btn btn-success' %>
    <% end %>
    <%= link_to 'CALNCEL', matches_path, :class => "btn btn-warning" %>
  </div>
  
<% end %>

app/views/matches/_table.html.erb
        <% @matches.each do |match| %>
          <tr>
            <td><%= match.day %></td>
            <td><%= Player.find(match.player1_id).name_with_initial %></td>
            <td><%= match.player1_res %></td>
            <td> : </td>
            <td><%= match.player2_res %></td>
            <td><%= Player.find(match.player2_id).name_with_initial %></td>
            <td><%= link_to 'Edit', edit_match_path(match) %></td>
            <td><%= link_to 'Delete', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>

app/views/matches/edit.html.erb
<div class="panel panel-warning">
  <div class="panel-heading">
    <h3 class="panel-title">Editing Match</h3>
  </div>
   <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">
  <div class="panel-heading">MATECHS
  </div>
  <div class="panel-body">
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Date</th>
          <th><%= select_tag "player1_id", options_for_select(@players.collect{ |u| [u.name_with_initial, u.id] }), include_blank: "Player1", :id => "player1_id" %></th>
          <th></th>
          <th>  </th>
          <th></th>
          <th><%= select_tag "player2_id", options_for_select(@players.collect{ |u| [u.name_with_initial, u.id] }), include_blank: "Player2", :id => "player2_id" %></th>
          <th colspan="2"></th>
        </tr>
      </thead>
      <tbody id="search_table">
        <%= render "matches/table" %>
      </tbody>
    </table>
  </div>
  </div>
</div>
<div><%= will_paginate @matches %></div><br>
<%= link_to 'Add new match', new_match_path, :class => "btn btn-info"  %>


<script>
    $('#player1_id').change(function(){
      var p1 = $("#player1_id").val();
      var p2 = $("#player2_id").val();
      $.ajax({
            type: 'GET',
            url: '/matches/search',
            data: { player1_id: p1, player2_id: p2 }
        });
    });
    $('#player2_id').change(function(){
      var p1 = $("#player1_id").val();
      var p2 = $("#player2_id").val();
      $.ajax({
            type: 'GET',
            url: '/matches/search',
            data: { player1_id: p1, player2_id: p2 }
        });
    });
</script>

app/views/matches/new.html.erb
<div class="panel panel-success">
  <div class="panel-heading">
    <h3 class="panel-title">New Metch</h3>
  </div>
   <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/matches/search.js.erb
$('#search_table').html("<%= j render(:partial => 'matches/table') %>");